apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.1.1"

    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        alertmanager:
          alertmanagerSpec:
            secrets:
              - alertmanager-email-secret
          config:
            global:
              smtp_smarthost: "smtp.gmail.com:587"
              smtp_from: "lyngochieu0405@gmail.com"
              smtp_auth_username: "lyngochieu0405@gmail.com"
              smtp_auth_password: /etc/alertmanager/secrets/alertmanager-email-secret/smtp_password

            route:
              group_by:
                - alertname
              receiver: email

            receivers:
              - name: email
                email_configs:
                  - to: "lyngochieu0405@gmail.com"
                    send_resolved: true

              - name: "null"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true